name: flutter_secure_keyboard
description: Mobile secure keyboard to prevent KeyLogger attack and screen capture.
version: 4.0.0
homepage: https://github.com/Dev-hwang/flutter_secure_keyboard

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.flutter_secure_keyboard
        pluginClass: FlutterSecureKeyboardPlugin
      ios:
        pluginClass: FlutterSecureKeyboardPlugin
